### ISSUE TITLE
iOS Safari 16.x 系で Sora DevTools 経由で背景ぼかしを使うと切断される

### ISSUE THREAD

**Issue by voluntas** [shiguredo/media-processors#335]
**バグを説明してください**

iOS Safari 16.x 系で [Sora DevTools](https://github.com/shiguredo/sora-devtools) で背景ぼかし機能を利用して Sora に接続すると 10 秒程度でリロードされる

**期待する動作**

リロードされないで、正常に使い続けられる。

環境
---

iOS: 16.4.1(a)

手順
---

1. iOS の Safari で devtools を開く
2. blurRadius に weak を設定する
3. 接続後 10 秒ほど待つとリロードされる

---

これは直接は MediaProcessors とは関係ないかもしれませんが、何かしらの影響は受けていると判断しています。

**Comment by kounoike** [comment]
「一定時間」をもう少し詳しくお願いします。
10分なのか1時間なのか、10分なら必ず10分なのか10分だったり30分だったりなのか、とか。

**Comment by miosakuma** [comment]
こちら、最新バージョンの iOS で再現しなくなったため、複数機種で調査を行いました。
結論として iOS / iPad OS が 16.4 系のときのみ発生する問題のようです。

最新の iOS / iPad OS で問題ないこと、特定の OS バージョンの問題であることからこのイシューはクローズします。

発生した
- iPad Air (iPadOS 16.4)
- iPhone 12 mini (iOS 16.4.1(a))
- iPhone SE (iOS 16.4.1)

発生しない
- iPad mini 6 (iPadOS 16.3.1)
- iPhone12 Pro Max (iOS 16.5)
- iPad Pro 12.9 (M2) (iPadOS 16.5)
- iPhone 12 mini (iOS 16.4.1(a)) -> 発生した端末をアップデートしてリロードされないことを確認
