### ISSUE TITLE
Sora DevTools 経由で 1080p で 3000 kbps 程度で背景ぼかしを利用した場合、遅延が発生する

### ISSUE THREAD

**Issue by voluntas** [shiguredo/media-processors#336]
**バグを説明してください**

[Sora DevTools](https://github.com/shiguredo/sora-devtools) 経由で 1080p で 3000 kbps 程度で背景ぼかしを利用した場合、遅延が発生する

**期待する動作**

遅延が発生しない。

---
これは直接は MediaProcessors とは関係ないかもしれませんが、何かしらの影響は受けていると判断しています。

**Comment by kounoike** [comment]
実験したところ処理無しで60ms程度だった環境で、背景ぼかしありにすると500ms程度遅延してます。
ライト補正でも発生していて、SelfieSegmentationをかけているmedium/strongでは300ms程度、かけていないweakだと60ms程度の遅延です。

カメラ→加工→ローカルビデオ→(Sora)→リモートビデオのはずなのに、加工の処理時間の違いがローカルビデオ⇔リモートビデオで遅延に影響するのは何故だろう？🤔

## 準備

OBSでブラウザソースを使い、以下のページを表示し、仮想カメラを開始する
https://narikakun.net/tool/ntp_ms.html

カスタムCSSを以下に変更する
```
body { background-color: rgba(255, 255, 255, 255); margin: 0px auto; overflow: hidden; }
```

## 実験手順

Sora DevToolsをsendonly/recvonlyの2つ開く。
接続して両方が同時に写るスクリーンショットを撮る。
（n=1ですけど簡易的な実験ということで・・・）

## 実験1: 

1080p/30fps/H.264/3000bps/blurRadius:未指定/lightAdjustment:未指定

（上: sendonly側、下:recvonly側）
<img width="1445" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/ded82f57-74cd-49d5-98f0-e80520f49a38">

## 実験2:

1080p/30fps/H.264/3000bps/blurRadius:weak/lightAdjustment:未指定

<img width="1432" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/c34567ee-8cb2-4fce-81c8-46b6dc3c8d99">

※videoCodecType、videoBitRateを変化させても同じような傾向

##  実験3:

1080p/30fps/H.264/3000bps/blurRadius:未指定/lightAdjustment:weak

<img width="1410" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/2ac209e5-bf14-444c-94a5-5f2e10afff9a">

## 実験4:

1080p/30fps/H.264/3000bps/blurRadius:未指定/lightAdjustment:medium

<img width="1445" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/94eacb28-3ec2-4bea-bd0c-d6c589326d0d">

**Comment by sile** [comment]
FYI ですが、以前に試した時には 5~10 秒くらいの遅延が発生することもありました。発生する人は WiMAX (ここは不確か) などを使っていて、通信環境は不安定だった印象があります。

**Comment by sile** [comment]
再現方法について調査を行い、進展があったので記載します。

- 再現環境:
  - OS: macOS Ventura 13.4
  - Chrome: 114.0.5735.106
- 再現手順: 以下の条件で Devtools ([2023.1.0-canary.12](https://github.com/shiguredo/sora-devtools/releases/tag/2023.1.0-canary.12)) から配信を行うと、視聴側で遅延が徐々に蓄積していきます
  - role: sendonly
  - videoBitrate: 5000
  - resolution: 720p
  - blurRadius: weak
- 視聴側は Devtools ではなくても可
- 配信側のローカル表示では遅延はしません
  - ただし、全体的に動作が遅くなって何らかのキューが詰まっている気配があります（e.g., 「disconnect」ボタンを押しても切断までに時間が掛かる）
- Devtools 経由ではなく、[gist](https://gist.github.com/sile/c9d4eef2397ba5fccd784e471b948858) の例のように sora-js-sdk を使って直接配信した場合には遅延は蓄積しません

 まとめると media-processors というよりは devtools の方に問題ある可能性が高そう、という状況です。

以下に、再現時のスクリーンショットを載せておきます:
- 右上: 配信ソースの仮想カメラ映像を合成している OBS
- 左上: sora-js-sdk (上の gist コード）を使って直接 blur 映像を配信しているページ（sendonly)
- 左下: devtools を使って blur 映像を配信しているページ (sendonly)
- 右真ん中: sora-js-sdk から受信した映像を表示
- 右下: devtools から受信した映像を表示 => 遅延している

![image](https://github.com/shiguredo/media-processors/assets/181413/dc3f9e94-6992-49ad-9363-f1a6377095ea)

**Comment by sile** [comment]
さらに調査を行ったところ devtools 固有の特別な問題があるというよりは「もともとカツカツだった blur 処理に加えて devtools 分の（若干の）オーバーヘッドが加わったことで間に合わなくなり遅延が蓄積していった」というシナリオが妥当そうに思えてきています。

media processors のコードとサンプルを修正して（m1 macbook pro の chrome で）いろいろと確認した結果を列挙すると、
- 解像度が 640x360 なら blur の有無関係なく 30 fps 出る
- 解像度が 1280x720 なら blur がない場合には 30 fps 出るけど、 blur があると 14 fps になる
  - **blur がない場合** では VirtualBackgroundProcessor は適用するけど、その画像処理部分をコメントアウトしてオリジナルの `ImageData` インスタンスをそのまま返すようにしている
  - 詳細は未把握だがどうやら breakout box の中で重い処理を走らせると、それに応じた FPS の調整が自動で行われる模様
- なお 1280x720 で blur がある場合には、下記の画像（chrome のパフォーマンストレース結果）に示されているように処理時間がカツカツ（複数のタスクの間に空きがない）でかなり余裕がない状態となっている
- => ただでさえカツカツなのに、そこに devtools 分の負荷が加わって溢れた、というのがあり得そう

![image](https://github.com/shiguredo/media-processors/assets/181413/92d202f6-983c-41a0-9f74-6cb645309513)

そのため、この件の対処としては、以下の二つがあり得るかと思っています:
- `VirtualBackgroundProcessor` の処理自体の高速化（どうやらぼかし処理がかなり重い模様）
-  処理がどうしても間に合わない場合には FPS を自動で（media processors のレイヤーでも）落とすようにする（遅延よりはマシなので）

それぞれの詳細については別に issue を起票して、そこに記載します。

**Comment by sile** [comment]
https://github.com/shiguredo/media-processors/pull/347 によって処理が高速化して遅延は解消したので issue はクローズします
