### ISSUE TITLE
背景ぼかし処理を高速化する

### ISSUE THREAD

**Issue by sile** [shiguredo/media-processors#345]
https://github.com/shiguredo/media-processors/issues/336 で報告されている問題への対処として、背景ぼかし処理の高速化を検討します（問題の詳細や再現環境・手順については #336 を参照してください）。

### 課題

現在、 `VirtualBackgroundProcessor` では背景ぼかしを行う際に、ブラウザが Safari 以外の場合にはキャンバスコンテキストにフィルタを設定することで行っています。

```javascript
canvasCtx.filter = `blur(${options.blurRadius}px)`;
```

ただし、この方法を使った場合は（少なくとも Chrome では）フィルタ適用後のキャンバスから `getImageData()` を使って画像データを取得する際にかなりの時間が掛かることが判明しました（720p の場合に 70 ms 程度）。
ぼかしではなく画像で背景を置換した場合や、ぼかしに StackBlur ライブラリ（Safari の場合にはフィルター機能がないためこれで代替している）を使った場合には、もっと短い時間で済みます。
以下は、それぞれの方法での処理速度を FPS の観点で計測した場合の参考値です（入力解像度は 720p、FPS は 30、いずれも Chrome で実行）:
- フィルター機能でぼかした場合: 14 fps
- StackBlur でぼかした場合: 28 fps
- ぼかしではなく画像を使った場合: 30 fps 

フィルター機能を使った場合が明らかに遅いため、何らかの方法でこれを改善したいと考えています。

### 対応案

一番簡単な方法は Safari 以外でも StackBlur を使うようにする、といったことが考えられます。
ただし、これでも 720p の場合には 30fps が達成できていないので、 LightAdjustmentProcessor と同じようにぼかし処理部分を Zig (SIMD) で実装することで高速化できないかは試してみたいです。

また、余裕があれば Google Meet では背景ぼかしをどのように実現しているのかも調査しておきたいと考えています。

**Comment by kounoike** [comment]
今だとGoogle Meetは解析対策をしていてあまり分からないと思います。
1年以上前だと普通にmediapipeのpbtxtだかをダウンロードしていて、https://viz.mediapipe.dev/ で見るとすべての処理が`*_gpu`となっていて、CPU/GPU間のメモリ転送が無いようにしていたようです。

blurが速くなるかどうか手っ取り早く試すのであればOpenCVを使うのも良いかもしれないですね。

**Comment by sile** [comment]
なるほどです。情報ありがとうございます。
急ぎではないのですがこの件と #346 を @kounoike さんにお任せしてしまってもいいでしょうか？

**Comment by kounoike** [comment]
どこまで出来るか分からないですが、一旦引き受けます。
[2022.1.0](https://github.com/shiguredo/media-processors/blob/virtual-background-2022.1.0/packages/virtual-background/src/virtual_background.ts#L174) の頃はcanvasからVideoFrameを作っていて、この頃は高速だったっぽいですね。

[2022.5.0](https://github.com/shiguredo/media-processors/blob/virtual-background-2022.5.0/packages/virtual-background/src/virtual_background.ts#L327-L336) のコメントの問題が気になりますが、一度状況確認（処理時間＆結果の不整合）でcanvasから直接VideoFrameを作ってみようかと思います。

**Comment by kounoike** [comment]
@sile 自分の環境では特に問題ないように見えますが、現在のChromeでも下記コメントの問題は起こるのでしょうか？

>    // `VideoFrame` の第一引数に `this.canvas` を直接渡したり、
>    // `this.canvas.transferToImageBitmap()` を使って `ImageBitmap` を取得することも可能だが、
>    // この方法だと環境によっては、透過時の背景色やぼかしの境界部分処理が変になる現象が確認できているため、
>    // ワークアラウンドとして、一度 `ImageData` を経由する方法を採用している
>    //
>    // `ImageData` を経由しない場合の問題としては https://bugs.chromium.org/p/chromium/issues/detail?id=961777 で
>    // 報告されているものが近そう

**Comment by sile** [comment]
性能確認ありがとうございます。全然違いますね...。
コメントの問題はちょっと再現状況が複雑だった覚えがあるので、来週にまた確認してみます。
ただ、もしまだ再現するとしても、ここまで性能差があるなら ImageData を使うのは止めた方がいいかもしれないですね...（問題事態は映像のすみに黒っぽい枠がかかる、といった比較的目立たないものでした）。

**Comment by kounoike** [comment]
SafariのときのStackBlurが遅い問題が未解決ですが、これはWebGLを使った方が良さそうな気がします。
ついでにlight-adjustmentのシャープネス処理もWebGLにしちゃえば良さそうですね。

**Comment by sile** [comment]
WebGL を使うのは確かにありかもですね。

過去の問題再現を試してみましたが、virtual-background-2022.4.2 のタグと #347 のブランチで再現しました。
現象としては devtools で以下の映像のようにちらつきが発生します:

https://github.com/shiguredo/media-processors/assets/181413/5f9dd823-645a-49a3-84cd-1817cdc1afdf

以下に再現手順を記載しますので @kounoike さんの環境でも発生するかどうかを一度試して頂ければと思います。

### 再現環境

- macOS: Apple M1 Max, Ventura 13.4.1)
   - 今回は未確認ですが、過去には Windows でも再現していたようです
- Chrome: 114.0.5735.133

### 再現手順

#### 1. media-processors と sora-devtools のビルド＆サーバ起動

```console
// media-processors をビルド
$ gh repo clone shiguredo/media-processors
$ cd media-processors
$ gh pr checkout 347
$ npm install
$ npm run build
$ cd ..

// devtools をビルド＆起動 (3333 ポートで HTTP サーバが起動する）
$ gh repo clone shiguredo/sora-devtools
$ cd sora-devtools
$ git checkout 2023.1.0
$ npm add -d  ../media-processors/packages/virtual-background/
$ npm install
$ cp ../media-processors/node_modules/@shiguredo/virtual-background/dist/* public/
$ npm run dev
```

#### 2. Chrome で devtools にアクセス

1. 以下の URL を二つのタブで開く
   - http://localhost:3333/devtools?channelId=sora&role=sendrecv&audio=false&video=true&debug=false&videoBitRate=15000&videoCodecType=VP8&resolution=1080p%20(1920x1080)&frameRate=30&blurRadius=weak
   - bitrate=15 Mbps, resolution=1920x1080, FPS=30, blur=weak
   - シグナリング URL は適当なものを設定する
2. 両方のタブで「connect」ボタンを押す
3. 数秒後にほぼ 100% ちらつきが発生する（しばらくして収まることもある）

**Comment by sile** [comment]
以下、参考までに過去の調査時に自分用に残したログの転載になります。

---

> - アルファチャンネル付きで完全に透過する画像を描画した場合、devtools だと透過部分が黒になるが、media-processors の example だと白になる
>   - かつ、透過部分が黒になる場合には、この issue にあるようにチラつくことがある（透過部分の黒と白が定期的に入れ替わる）
> - 仮想背景処理時に、透過部分が生じないように OffscreenCanvas を単色で埋めたら、ちらつきは発生しないように見える
> - 仮想背景処理時に、 OffscreenCanvas に何も描画せずに、そのまま VideoFrame を作成してもちらつきは発生する（完全透過の状態？）
> - => おそらく、アルファチャンネル（や blur フィルタ）を含んだ VideoFrame の処理が高負荷時(?) におかしくなっている？（仮想背景処理自体はそこまで影響はなさそうな印象）

--

> 以下のように完全透過なビットマップを生成・使用した場合には、映像の背景も真っ白になってチカチカしないので、やっぱり OffscreenCanvas が悪さをしているのかもしれない 🤔 
```typescript
    const arr = new Uint8ClampedArray(1920 * 1080 * 4);
    for (let i = 0; i < arr.length; i += 4) {
      arr[i + 0] = 100; // R value  (完全透過なので何の値でも良い）
      arr[i + 1] = 100; // G value
      arr[i + 2] = 100; // B value
      arr[i + 3] = 0; // A value  (完全透過)
    }
    const data = new ImageData(arr, 1920, 1080);
    const bitmap = await createImageBitmap(data);
    controller.enqueue(new VideoFrame(bitmap, { timestamp, duration }));
```

--

> 以下のような感じで `OffscreenCanvas` の更新は一度だけにして、その後最初の描画結果のビットマップを使いまわした場合には、白・黒反転してチカチカする。
```typescript
if (this.bitmap === undefined) {
  // OffscreenCanvas を初期化
  this.canvasCtx.save();
  this.canvasCtx.clearRect(0, 0, this.canvas.width, this.canvas.height);
  this.canvasCtx.restore();
  
  this.bitmap = this.canvas.transferToImageBitmap();
}

const bitmap = await createImageBitmap(this.bitmap);
controller.enqueue(new VideoFrame(bitmap, { timestamp, duration }));
```

-- 

> VideoFrame 生成部分を一度 ImageData を経由するようにしたら、ちらつきや四隅の黒枠はなくなったように見える:
```typescript
// OK
const data = this.canvasCtx.getImageData(0, 0, this.canvas.width, this.canvas.height);
const bitmap = await createImageBitmap(data);
controller.enqueue(new VideoFrame(bitmap, { timestamp, duration }));

// NG (今の media-processors の方式)
controller.enqueue(new VideoFrame(this.canvas, { timestamp, duration }));

// NG (明示的に ImageBitmap に変換する)
controller.enqueue(new VideoFrame(this.canvas.transferToImageBitmap(), { timestamp, duration }));
```

--

> 現象としては https://bugs.chromium.org/p/chromium/issues/detail?id=961777 で報告されているバグがかなり近そう。ただし、当面対応される予定はなさそう。
`ImageData` を経由する方法でも性能劣化は特に見られなかったので、こちらのワークアラウンドを採用するので良さそうな印象。

**Comment by kounoike** [comment]
再現できないですね・・・
M2 Macbook Air/Chrome 114で試してますが映像ソースの関係ですかね

あと、なぜかOBSの仮想カメラが1280x720しか出ない・・・

<img width="554" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/1f8b89e3-5f30-4b03-a5ae-be3ebeb397c9">

**Comment by kounoike** [comment]
再現したっぽいです。
背景のbig buck bunnyが重要なのですね

ただ、sora-devtools.shiguredo.jp（=ImageData経由）でも発生しています。

https://github.com/shiguredo/media-processors/assets/6997928/155812dc-4515-44df-80e6-2b4717f265bc

上記はsora-devtools.shiguredo.jpで試したものです。

**Comment by sile** [comment]
なんと、自分の環境では sora-devtools.shiguredo.jp では発生しないので不思議ですね...。
ぼかしの時に処理が遅くて詰まるのが（ちらつきが発生しない）原因かもしれない、と思い media-processors の develop で常に StackBlur を使うように修正して試してみましたが、それでも再現しませんでした。
（なお PR ブランチでは FPS は 15 でも再現してので、ここでも 15 で試しました）
環境依存の何かがありそうで厄介ですね...。

ちなみに、手元の mac だと big buck bunny ではなく静止画でも以下のように再現します。

https://github.com/shiguredo/media-processors/assets/181413/844187be-eabf-4e66-bd20-47f864571543

また Windows 11 で試してみたところ、ちらつきは発生せずに黒枠が出るだけでした（こちらの現象も sora-devtools.shiguredo.jp では再現せず）。
分かりにくいですが、以下の動画では「connect」押して再接続した直後に（数フレーム遅れくらいで？）黒枠が発生して、以後はそのままになっています。

https://github.com/shiguredo/media-processors/assets/181413/36456c1a-aa93-4d82-bf12-3ca0ed5e5fc1

**Comment by sile** [comment]
環境依存度が高そうなので #347 も含めてどんな感じで進めるかが少し悩ましいですね。
すぐに思いつく方針としては、
- a) ちらつき問題と遅延問題は別物として考えて、先に高速化 PR のレビュー・マージを進める
  - m1 mac (?) でちらつきが発生するようになるリスクはあるけど許容する
- b) 先にちらつき問題を調査して、高速化 PR の中でちらつきが発生しないように対処を行なってしまう
  - 環境依存度が高い問題ということもあって PR のマージが結構先になってしまうリスクがありそう
- c) ぼかし処理の高速化は現状の ImageData ベースで行い（e.g., 単に常に StackBlur を使うようにする）、その後に b の方針で取り組む
  - 堅実ではあるけど全体として無駄な手間が増える

上記以外の方針検討も含めて、具体的にどのように進めるかは @kounoike さんにお任せできればと考えているので、意見を貰えると助かります 🙏

**Comment by kounoike** [comment]
RGB値が極端なOBS仮想カメラでの結果はあまり気にしないで、自然画像（特に人物上半身）のときにどれくらい影響あるかで判断した方が良さそうです。
私の環境では自分を写した場合はあまり気にならなかったですね。
どちらかというとselfie_segmentationが生成するマスクが不安定で、そっちの影響でちらつくのが気になるくらいです。
（ちなみにそれは昔見たGoogle Meetのpbtxtだと前のフレームのマスクを使って上手いこと軽減してました）

後は単なる思い付きですけど、OffscreenCanvasの問題ならChromeでも敢えて普通のCanvasを使っちゃうとか？

**Comment by kounoike** [comment]
<img width="1460" alt="image" src="https://github.com/shiguredo/media-processors/assets/6997928/1a828ee0-181e-424e-9c98-f197c4aaa57f">

2023-06-27.10.02.58.movのちらつき前後の2コマを拡大して見てました。
左のコマは画像境界を固定値0で処理したblurって感じで自然です。
右のコマは最外周ピクセルが(131, 131, 136)のグレーなのが謎な感じです。固定値0でblurかけた後に固定値255でもう一回blurかけた・・・というわけでもなさそう。

**Comment by sile** [comment]
> 私の環境では自分を写した場合はあまり気にならなかったですね。

了解です。それなら #347 はもうレビューしてしまいますね。

> OffscreenCanvasの問題ならChromeでも敢えて普通のCanvasを使っちゃうとか？

OffscreenCanvas を使っている強い理由はないので、これで解消するなら普通の Canvas を使うのはアリだと思います。

> どちらかというとselfie_segmentationが生成するマスクが不安定で、そっちの影響でちらつくのが気になるくらいです。

確かにこれも気になると言えば気になるので軽減できると嬉しいですね。

**Comment by kounoike** [comment]
Chromeについては #347 で対応OK、Safariの場合にStackBlurが遅い問題が残っているのでこのIssueはまだ閉じない方が良いかと。
Firefoxのことは忘れてましたけど、Unsupported platformですね

**Comment by sile** [comment]
FYI ですが OffscreenCanvas とちらつきの関係を調べてみようと動かしてみたら、そもそも（上記の）手元の環境で問題が再現しなくなっていました 🤔 (develop と 2022.4.2 の両方で）
Chrome のバージョンが  114.0.5735.198 と僅かに上がっているのが影響しているのかもしれないのですが、理由は分かっていないです。
いずれにせよ、また再現するまでいったん忘れて良さそうな雰囲気ではあります。

**Comment by sile** [comment]
今日（virtual-background-2023.2.0 で）試したらちらつきが再現しました 🤔

**Comment by sile** [comment]
https://github.com/shiguredo/media-processors/pull/347 で対応済み
