### ISSUE TITLE
仮想背景処理が間に合わない場合にはフレームレートを下げる

### ISSUE THREAD

**Issue by sile** [shiguredo/media-processors#346]
https://github.com/shiguredo/media-processors/issues/336 で報告されている問題への対処として、仮想背景処理が間に合わない場合にはフレームレートを自動で下げることを検討します（問題の詳細や再現環境・手順については #336 を参照してください）。

### 課題

仮想背景処理はそこそこ重い処理であるため、入力映像解像度が大きかったり、実行するマシンのスペックが高くなかったりすると、処理が間に合わない可能性があります。
処理が間に合わなかった場合には #336 で報告されているような遅延の蓄積に繋がる恐れがありますが、それはユーザ体験として良くないので、代わりにそのようなケースではフレームレートを自動で下げてしまうことを検討したいと考えています。

### 検討事項

- そもそも本当にこの機能が必要か
  - #345 である程度の高速化は見込めるのでそれで十分な可能性もなくはない
- 具体的な挙動をどうするか
  - 例えば「最後のフレームの処理時刻と処理所要時間を覚えておいて、カツカツだったら次のフレームをスキップする」といった各フレームを独立して扱うようなものにするのか、それとも処理時間の統計値を管理して「期待最大フレームレート」のような値を満たすようにするのか（前者の方が実装は楽で柔軟だけど、フレームの落とし方がマチマチになるので、視聴者の違和感が大きくなる可能性はある）
- フレームをドロップするのか、それとも一つ前のフレームの（処理後の）画像を流用するようにするのか
  - 前者の方が負荷は小さくなるけど、手元の環境で軽く試した時には（なぜか）受信側で遅延が蓄積されるケースを見かけることがあった（ネットワークが不安定でパケロスが比較的多い場合）
     - 追記: 再現性が怪しいのでいったんこれは忘れてもいいかもしれません
  - 後者の方は若干無駄ではあるけど、外から見た動作としては従来通りなので変な不確定要因が入ることを防ぐことができそう
- オプションでどの程度動作を制御できるようにすべきか（e.g., デフォルトで有効にするのかどうか）　
- 仮想背景固有にするのか、それともで映像系全般の共通処理として実装するのか

**Comment by sile** [comment]
参考までも手元で過負荷時にフレームレートを下げる処理（正確にはフレーム流用処理）を試した時の差分です:
```diff
diff --git a/packages/virtual-background/src/virtual_background.ts b/packages/virtual-background/src/virtual_background.ts
index e5b9329..120e936 100644
--- a/packages/virtual-background/src/virtual_background.ts
+++ b/packages/virtual-background/src/virtual_background.ts
@@ -195,14 +195,32 @@ class VirtualBackgroundProcessor {
       this.updateOffscreenCanvas(results, canvasCtx, blurCanvasCtx, options);
     });
 
+    let lastFrameProcessDuration = 0;
+    let lastTime = 0;
+    let lastImage: ImageData | undefined;
+
     // 仮想背景処理を開始
     return this.trackProcessor.startProcessing(track, async (image: ImageData) => {
+      const startTime = performance.now();
+      if (startTime - lastTime < lastFrameProcessDuration / 10) {
+        // 最後のフレームを処理してからすぐ（フレーム処理時間の 1/10 未満）に次のフレームが来た場合には、
+        // 余裕がないものとしてフレーム処理をスキップする（一つ前の処理後のフレームをそのまま流用する）
+        //
+        // TODO: ここでフレームをそもそも破棄する場合には video-track-processor 側も修正する必要がある
+        return lastImage;
+      }
+
       const { width, height } = image;
 
       // @ts-ignore TS2322: 「`image`の型が合っていない」と怒られるけれど、動作はするので一旦無視
       await this.segmentation.send({ image });
 
-      return canvasCtx.getImageData(0, 0, width, height);
+      const processedImage = canvasCtx.getImageData(0, 0, width, height);
+      lastTime = performance.now();
+      lastFrameProcessDuration = lastTime - startTime;
+      lastImage = processedImage;
+
+      return processedImage;
     });
   }
 ```

**Comment by kounoike** [comment]
フレームレートの調整をする前に、フレームレートと処理時間を記録して、外部から取得出来るようにしておくといいかもしれません。
調整はその数値や背景ぼかしの高速化の結果を見てから考えるということでどうでしょう？

**Comment by sile** [comment]
提案ありがとうございます。確かにその進め方が良さそうです。

**Comment by sile** [comment]
https://github.com/shiguredo/media-processors/pull/347 によって背景ぼかし処理自体が高速化して、フレームレートを下げる処理を入れる必要性がなくなったため、issue はクローズします
